version: 0.2

phases:
  build:
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "Installing dependencies into src file"
      - npm i
      - npm run build
      - cd dist
      - zip -r lambda.zip .

artifacts:
  files:
    - "dist/lambda.zip"
